# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9469b4872f5e051e477b8c224de477337e5e3bda477c48d2b90596e9c8c0e5b7b3d5e73e604117da7fa0b8620ff5fff204ebf10d9b915c5337a710857525c0c

test:
  secret_key_base: 539f9282dc66ef3e62c6a226a40c40841fe80aa766ea3146096f824fe93c54c3993a0ad6efc9a0391fa9aabb350b686471c90025e462cdeec58ff66e42a792a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
